services:
  - type: web
    name: essay-scoring-app
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn Automatic_English_Essay_Scoring_Algorithm_Based_On_Ml.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: essay-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
